{% set version = "1.4-3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-coin
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/coin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/coin/coin_{{ version }}.tar.gz
  sha256: 8a6302dbf3ef570cd9f69ce7b6cd3d3b928dc776f840bbd767af132e0080b974

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-matrixstats              # [build_platform != target_platform]
    - r-libcoin                  # [build_platform != target_platform]
    - r-multcomp                 # [build_platform != target_platform]
    - r-survival                 # [build_platform != target_platform]
    - r-mvtnorm                  # [build_platform != target_platform]
    - r-modeltools               # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-libcoin >=1.0_5
    - r-matrixstats >=0.54.0
    - r-modeltools >=0.2_9
    - r-multcomp
    - r-mvtnorm >=1.0_5
    - r-survival
  run:
    - r-base
    - r-libcoin >=1.0_5
    - r-matrixstats >=0.54.0
    - r-modeltools >=0.2_9
    - r-multcomp
    - r-mvtnorm >=1.0_5
    - r-survival

test:
  commands:
    - $R -e "library('coin')"           # [not win]
    - "\"%R%\" -e \"library('coin')\""  # [win]

about:
  home: http://coin.r-forge.r-project.org
  license: GPL-2.0-only
  summary: Conditional inference procedures for the general independence problem including two-sample, K-sample (non-parametric ANOVA), correlation, censored, ordered and multivariate problems.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: coin
# Version: 1.3-1
# Date: 2019-08-22
# Title: Conditional Inference Procedures in a Permutation Test Framework
# Authors@R: c(person("Torsten", "Hothorn", role = c("aut", "cre"), email = "Torsten.Hothorn@R-project.org", comment = c(ORCID = "0000-0001-8301-0471")), person("Henric", "Winell", role = "aut", comment = c(ORCID = "0000-0001-7995-3047")), person("Kurt", "Hornik", role = "aut", comment = c(ORCID = "0000-0003-4198-9911")), person(c("Mark", "A."), "van de Wiel", role = "aut", comment = c(ORCID = "0000-0003-4780-8472")), person("Achim", "Zeileis", role = "aut", comment = c(ORCID = "0000-0003-0918-3766")))
# Description: Conditional inference procedures for the general independence problem including two-sample, K-sample (non-parametric ANOVA), correlation, censored, ordered and multivariate problems.
# Depends: R (>= 3.4.0), survival
# Imports: methods, parallel, stats, stats4, utils, libcoin (>= 1.0-0), matrixStats (>= 0.54.0), modeltools (>= 0.2-9), mvtnorm (>= 1.0-5), multcomp
# Suggests: xtable, e1071, vcd, TH.data (>= 1.0-7)
# LinkingTo: libcoin (>= 1.0-0)
# LazyData: yes
# NeedsCompilation: yes
# ByteCompile: yes
# License: GPL-2
# URL: http://coin.r-forge.r-project.org
# Packaged: 2019-08-27 09:16:05 UTC; hothorn
# Author: Torsten Hothorn [aut, cre] (<https://orcid.org/0000-0001-8301-0471>), Henric Winell [aut] (<https://orcid.org/0000-0001-7995-3047>), Kurt Hornik [aut] (<https://orcid.org/0000-0003-4198-9911>), Mark A. van de Wiel [aut] (<https://orcid.org/0000-0003-4780-8472>), Achim Zeileis [aut] (<https://orcid.org/0000-0003-0918-3766>)
# Maintainer: Torsten Hothorn <Torsten.Hothorn@R-project.org>
# Repository: CRAN
# Date/Publication: 2019-08-28 11:50:06 UTC
