{% set version = '1.2-2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-coin
  version: {{ version|replace("-", "_") }}

source:
  fn: coin_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/coin_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/coin/coin_{{ version }}.tar.gz
  sha256: d518065d3e1eb00121cb4e0200e1e4ae6b68eca6e249afc38bbffa35d24105bb

build:
  merge_build_host: True  # [win]
  number: 1000
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-modeltools >=0.2_9
    - r-multcomp
    - r-mvtnorm >=1.0_5
    - r-survival
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-modeltools >=0.2_9
    - r-multcomp
    - r-mvtnorm >=1.0_5
    - r-survival

test:
  commands:
    - $R -e "library('coin')"           # [not win]
    - "\"%R%\" -e \"library('coin')\""  # [win]

about:
  home: http://coin.r-forge.r-project.org
  license: GPL-2
  summary: Conditional inference procedures for the general independence problem including two-sample,
    K-sample (non-parametric ANOVA), correlation, censored, ordered and multivariate
    problems.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
